### ISSUE TITLE
Great idea (update soon?)

### ISSUE THREAD

**Issue by firmai** [dend/arxiv-sanity-feeds#1]
Hi, this is a great idea, is this still something that you want to maintain, I am not great with scraping, but it would be awesome to have a feed like this. Have you come across any other ways of doing it that might be easier to maintain?

**Comment by dend** [comment]
Thanks for the ping on this! I will be reviving this effort shortly, as I have a need for these papers myself.

**Comment by firmai** [comment]
Hey there, any idea what the bug might be, if so I can have quick stab at fixing it.

**Comment by dend** [comment]
@firmai not a bug per-se, I just need to point the service to a different API endpoint (moved to Digital Ocean from Azure). Thinking I can tackle this work this week!

**Comment by dend** [comment]
@firmai the feeds should be working once again!
